import { type FrameworkCatalogPickerConfig } from "@/lib/plugins";

export interface FrameworkCatalogItem {
  value: string;
  label: string;
  kind: string;
  keywords?: string[];
}

export interface FrameworkCatalog {
  id: string;
  title: string;
  description: string;
  items: FrameworkCatalogItem[];
}

const NIST_FAMILY_LABELS: Record<string, string> = {
  AC: "Access Control",
  AP: "Authority and Purpose",
  AT: "Awareness and Training",
  AU: "Audit and Accountability",
  CA: "Assessment, Authorization, and Monitoring",
  CM: "Configuration Management",
  CP: "Contingency Planning",
  IA: "Identification and Authentication",
  IR: "Incident Response",
  MA: "Maintenance",
  MP: "Media Protection",
  PE: "Physical and Environmental Protection",
  PL: "Planning",
  PM: "Program Management",
  PS: "Personnel Security",
  PT: "PII Processing and Transparency",
  RA: "Risk Assessment",
  SA: "System and Services Acquisition",
  SC: "System and Communications Protection",
  SI: "System and Information Integrity",
  SR: "Supply Chain Risk Management",
};

const NIST_CONTROL_IDS = [
  "AC-1",
  "AC-11",
  "AC-14",
  "AC-17",
  "AC-18",
  "AC-19",
  "AC-2",
  "AC-20",
  "AC-22",
  "AC-3",
  "AC-4",
  "AC-5",
  "AC-6",
  "AC-7",
  "AC-8",
  "AP-1",
  "AP-2",
  "AU-11",
  "AU-2",
  "AU-3",
  "AU-4",
  "CA-3",
  "CA-7",
  "CM-2",
  "CM-3",
  "CM-6",
  "CP-9",
  "IA-2",
  "IA-5",
  "IR-5",
  "IR-6",
  "PE-10",
  "PE-11",
  "PE-12",
  "PE-13",
  "PE-14",
  "PE-15",
  "PE-2",
  "PE-3",
  "PE-6",
  "PE-8",
  "PE-9",
  "RA-2",
  "RA-5",
  "SA-9",
  "SC-12",
  "SC-13",
  "SC-28",
  "SC-7",
  "SI-2",
  "SI-3",
  "SI-4",
] as const;

const SOC2_CATEGORY_ITEMS: FrameworkCatalogItem[] = [
  { value: "security", label: "Security", kind: "category" },
  { value: "availability", label: "Availability", kind: "category" },
  { value: "confidentiality", label: "Confidentiality", kind: "category" },
  { value: "processing-integrity", label: "Processing Integrity", kind: "category" },
  { value: "privacy", label: "Privacy", kind: "category" },
];

const SOC2_GROUP_ITEMS: FrameworkCatalogItem[] = [
  { value: "CC1", label: "CC1 · Control Environment", kind: "group" },
  { value: "CC2", label: "CC2 · Communication and Information", kind: "group" },
  { value: "CC3", label: "CC3 · Risk Assessment", kind: "group" },
  { value: "CC4", label: "CC4 · Monitoring Activities", kind: "group" },
  { value: "CC5", label: "CC5 · Control Activities", kind: "group" },
  { value: "CC6", label: "CC6 · Logical and Physical Access", kind: "group" },
  { value: "CC7", label: "CC7 · System Operations", kind: "group" },
  { value: "CC8", label: "CC8 · Change Management", kind: "group" },
  { value: "CC9", label: "CC9 · Risk Mitigation", kind: "group" },
  { value: "A1", label: "A1 · Availability", kind: "group" },
  { value: "C1", label: "C1 · Confidentiality", kind: "group" },
  { value: "PI1", label: "PI1 · Processing Integrity", kind: "group" },
  { value: "P1", label: "P1 · Privacy", kind: "group" },
];

const SOC2_CONTROL_VALUES = [
  "A1.1",
  "CC1",
  "CC1.1",
  "CC1.2",
  "CC1.3",
  "CC1.4",
  "CC1.5",
  "CC2",
  "CC2.1",
  "CC2.3",
  "CC3",
  "CC3.1",
  "CC3.4",
  "CC4",
  "CC4.1",
  "CC4.2",
  "CC5",
  "CC5.1",
  "CC5.3",
  "CC6",
  "CC6.1",
  "CC6.2",
  "CC6.3",
  "CC6.4",
  "CC6.6",
  "CC6.7",
  "CC6.8",
  "CC7",
  "CC7.1",
  "CC7.2",
  "CC7.3",
  "CC7.4",
  "CC7.5",
  "CC8",
  "CC8.1",
  "CC9",
  "CC9.1",
  "CC9.2",
  "CC9.3",
] as const;

const CMMC_PRACTICE_IDS = [
  "AC.L1-3.1.1",
  "AC.L1-3.1.2",
  "AC.L2-3.1.1",
  "AC.L2-3.1.2",
  "AC.L2-3.1.20",
  "AC.L2-3.1.22",
  "AM.L2-3.4.1",
  "AM.L2-3.4.2",
  "AT.L2-3.2.1",
  "AT.L2-3.2.2",
  "AT.L2-3.2.3",
  "AU.L2-3.3.1",
  "AU.L2-3.3.2",
  "AU.L2-3.3.8",
  "CA.L2-3.12.1",
  "CA.L2-3.12.2",
  "CA.L2-3.12.4",
  "CM.L2-3.4.1",
  "CM.L2-3.4.2",
  "CM.L2-3.4.7",
  "IA.L1-3.5.1",
  "IA.L1-3.5.2",
  "IA.L2-3.5.1",
  "IA.L2-3.5.10",
  "IA.L2-3.5.2",
  "IA.L2-3.5.7",
  "IA.L2-3.5.8",
  "IR.L2-3.6.1",
  "IR.L2-3.6.2",
  "IR.L2-3.6.3",
  "MA.L2-3.7.1",
  "MA.L2-3.7.2",
  "MA.L2-3.7.5",
  "MP.L1-3.8.3",
  "MP.L2-3.8.1",
  "MP.L2-3.8.2",
  "PE.L1-3.10.1",
  "PE.L2-3.10.3",
  "PE.L2-3.10.4",
  "PS.L2-3.9.1",
  "PS.L2-3.9.2",
  "RE.L2-3.14.1",
  "RE.L2-3.14.2",
  "RM.L2-3.11.1",
  "RM.L2-3.11.2",
  "RM.L2-3.11.3",
  "SA.L2-3.14.1",
  "SA.L2-3.14.2",
  "SA.L2-3.14.6",
  "SC.L1-3.13.1",
  "SC.L2-3.13.11",
  "SC.L2-3.13.8",
  "SI.L1-3.14.1",
  "SI.L1-3.14.2",
  "SI.L2-3.14.4",
] as const;

const CCM_CONTROL_IDS = [
  "AES-25",
  "AIS-01",
  "AIS-02",
  "AIS-03",
  "AIS-04",
  "AIS-05",
  "AIS-06",
  "AIS-07",
  "AIS-08",
  "AIS-09",
  "AIS-10",
  "AIS-11",
  "AU-11",
  "BCR-01",
  "BCR-02",
  "BCR-03",
  "BCR-04",
  "BCR-05",
  "BCR-06",
  "BCR-07",
  "BCR-08",
  "BCR-09",
  "BCR-10",
  "BCR-11",
  "CCC-01",
  "CCC-02",
  "CCC-03",
  "CCC-04",
  "CCC-05",
  "CCC-06",
  "CCC-07",
  "CCC-08",
  "CCC-09",
  "CEK-01",
  "CEK-02",
  "CEK-03",
  "CEK-04",
  "CEK-05",
  "CEK-06",
  "CEK-07",
  "CEK-08",
  "CEK-09",
  "CEK-10",
  "CEK-11",
  "CEK-12",
  "CEK-13",
  "CEK-14",
  "CEK-15",
  "CP-10",
  "DCS-01",
  "DCS-02",
  "DCS-03",
  "DCS-04",
  "DCS-05",
  "DCS-06",
  "DCS-07",
  "DCS-08",
  "DCS-09",
  "DCS-10",
  "DCS-11",
  "DCS-12",
  "DSP-01",
  "DSP-02",
  "DSP-03",
  "DSP-04",
  "DSP-05",
  "DSP-06",
  "DSP-07",
  "DSP-08",
  "DSP-09",
  "DSP-10",
  "DSP-11",
  "DSP-12",
  "DSP-13",
  "GRC-01",
  "GRC-02",
  "GRC-03",
  "GRC-04",
  "GRC-05",
  "GRC-06",
  "GRC-07",
  "GRC-08",
  "GRC-09",
  "GRC-10",
  "GRC-11",
  "GRC-12",
  "GRC-13",
  "GRC-14",
  "HRS-01",
  "HRS-02",
  "HRS-03",
  "HRS-04",
  "HRS-05",
  "HRS-06",
  "HRS-07",
  "HRS-08",
  "HRS-09",
  "HRS-10",
  "IAM-01",
  "IAM-02",
  "IAM-03",
  "IAM-04",
  "IAM-05",
  "IAM-06",
  "IAM-07",
  "IAM-08",
  "IAM-09",
  "IAM-10",
  "IAM-11",
  "IAM-12",
  "IAM-13",
  "IAM-14",
  "IAM-15",
  "IAM-16",
  "IPY-01",
  "IPY-02",
  "IPY-03",
  "IPY-04",
  "IPY-05",
  "IVS-01",
  "IVS-02",
  "IVS-03",
  "IVS-04",
  "IVS-05",
  "IVS-06",
  "IVS-07",
  "IVS-08",
  "IVS-09",
  "IVS-10",
  "IVS-11",
  "IVS-12",
  "IVS-13",
  "LOG-01",
  "LOG-02",
  "LOG-03",
  "LOG-04",
  "LOG-05",
  "LOG-06",
  "LOG-07",
  "LOG-08",
  "LOG-09",
  "LOG-10",
  "LOG-11",
  "LOG-12",
  "LOG-13",
  "RSA-20",
  "SC-12",
  "SC-28",
  "SEF-01",
  "SEF-02",
  "SEF-03",
  "SEF-04",
  "SEF-05",
  "SEF-06",
  "SEF-07",
  "SEF-08",
  "SEF-09",
  "SEF-10",
  "SHA-25",
  "SHA-38",
  "SHA-51",
  "STA-01",
  "STA-02",
  "STA-03",
  "STA-04",
  "STA-05",
  "STA-06",
  "STA-07",
  "STA-08",
  "STA-09",
  "STA-10",
  "STA-11",
  "TVM-01",
  "TVM-02",
  "TVM-03",
  "TVM-04",
  "TVM-05",
  "TVM-06",
  "TVM-07",
  "TVM-08",
  "TVM-09",
  "TVM-10",
  "TVM-11",
  "TVM-12",
  "TVM-13",
  "UEM-01",
  "UEM-02",
  "UEM-03",
  "UEM-04",
  "UEM-05",
  "UEM-06",
  "UEM-07",
] as const;

const PCI_REQUIREMENT_ITEMS: FrameworkCatalogItem[] = [
  { value: "1", label: "1 · Network Security Controls", kind: "requirement" },
  { value: "2", label: "2 · Secure Configurations", kind: "requirement" },
  { value: "3", label: "3 · Stored Account Data", kind: "requirement" },
  { value: "4", label: "4 · Transmission Security", kind: "requirement" },
  { value: "5", label: "5 · Malicious Software", kind: "requirement" },
  { value: "6", label: "6 · Secure Development", kind: "requirement" },
  { value: "7", label: "7 · Access by Need to Know", kind: "requirement" },
  { value: "8", label: "8 · User Identification and Authentication", kind: "requirement" },
  { value: "9", label: "9 · Physical Access", kind: "requirement" },
  { value: "10", label: "10 · Logging and Monitoring", kind: "requirement" },
  { value: "11", label: "11 · Security Testing", kind: "requirement" },
  { value: "12", label: "12 · Security Policies and Programs", kind: "requirement" },
];

const PCI_MARCH_2025_ITEMS: FrameworkCatalogItem[] = [
  { value: "3", label: "3 · Stored Account Data", kind: "requirement" },
  { value: "5", label: "5 · Malicious Software", kind: "requirement" },
  { value: "6", label: "6 · Secure Development", kind: "requirement" },
  { value: "7", label: "7 · Access by Need to Know", kind: "requirement" },
  { value: "8", label: "8 · User Identification and Authentication", kind: "requirement" },
  { value: "10", label: "10 · Logging and Monitoring", kind: "requirement" },
  { value: "11", label: "11 · Security Testing", kind: "requirement" },
  { value: "12", label: "12 · Security Policies and Programs", kind: "requirement" },
  {
    value: "payment page",
    label: "Payment Page",
    kind: "category",
    keywords: ["11.6.1", "tamper detection"],
  },
];

const PCI_ROC_ITEMS: FrameworkCatalogItem[] = [
  { value: "executive summary", label: "Executive Summary", kind: "section" },
  { value: "appendices", label: "Appendices", kind: "section" },
  ...PCI_REQUIREMENT_ITEMS,
];

function controlPrefix(value: string): string {
  const [prefix] = value.split(/[-.]/);
  return prefix;
}

function dedupeItems(items: FrameworkCatalogItem[]): FrameworkCatalogItem[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item.value)) {
      return false;
    }
    seen.add(item.value);
    return true;
  });
}

const FRAMEWORK_CATALOGS: Record<string, FrameworkCatalog> = {
  "nist-800-53-controls": {
    id: "nist-800-53-controls",
    title: "NIST 800-53 Controls",
    description:
      "Select a NIST 800-53 family or a control ID sourced from the local framework command documentation.",
    items: dedupeItems([
      ...Object.entries(NIST_FAMILY_LABELS).map(([value, label]) => ({
        value,
        label: `${value} · ${label}`,
        kind: "family",
        keywords: [label],
      })),
      ...NIST_CONTROL_IDS.map((value) => ({
        value,
        label: value,
        kind: "control",
        keywords: [NIST_FAMILY_LABELS[controlPrefix(value)] ?? controlPrefix(value)],
      })),
    ]),
  },
  "soc2-controls": {
    id: "soc2-controls",
    title: "SOC 2 Controls",
    description:
      "Select a Trust Services category, criterion group, or specific control reference from the local SOC 2 docs.",
    items: dedupeItems([
      ...SOC2_CATEGORY_ITEMS,
      ...SOC2_GROUP_ITEMS,
      ...SOC2_CONTROL_VALUES.map((value) => ({
        value,
        label: value,
        kind: value.includes(".") ? "control" : "group",
      })),
    ]),
  },
  "soc2-control-groups": {
    id: "soc2-control-groups",
    title: "SOC 2 Control Groups",
    description:
      "Select one or more Trust Services categories or criterion groups for the auditor package scope.",
    items: dedupeItems([...SOC2_CATEGORY_ITEMS, ...SOC2_GROUP_ITEMS]),
  },
  "cmmc-practices": {
    id: "cmmc-practices",
    title: "CMMC Practices",
    description:
      "Select a CMMC practice ID from the practice references present in the bundled framework documentation.",
    items: CMMC_PRACTICE_IDS.map((value) => ({
      value,
      label: value,
      kind: "practice",
    })),
  },
  "csa-ccm-controls": {
    id: "csa-ccm-controls",
    title: "CSA CCM Controls",
    description:
      "Select a CSA CCM control ID from the local control references shipped with the framework plugin.",
    items: CCM_CONTROL_IDS.map((value) => ({
      value,
      label: value,
      kind: "control",
    })),
  },
  "pci-dss-requirements": {
    id: "pci-dss-requirements",
    title: "PCI DSS Requirements",
    description:
      "Select a top-level PCI DSS requirement. Sub-requirements can still be entered manually in the field.",
    items: PCI_REQUIREMENT_ITEMS,
  },
  "pci-dss-march-2025": {
    id: "pci-dss-march-2025",
    title: "March 2025 Scope",
    description:
      "Select a March 31, 2025 mandatory requirement area or the payment-page category.",
    items: PCI_MARCH_2025_ITEMS,
  },
  "pci-dss-roc-sections": {
    id: "pci-dss-roc-sections",
    title: "ROC Sections",
    description:
      "Select a top-level ROC section or PCI DSS requirement. Requirement-level detail can still be typed manually.",
    items: PCI_ROC_ITEMS,
  },
};

export function getFrameworkCatalog(
  catalogId: FrameworkCatalogPickerConfig["catalog"],
): FrameworkCatalog | null {
  return FRAMEWORK_CATALOGS[catalogId] ?? null;
}
